from pathlib import Path

ROOT_DIRECTORY_PATH = Path(__file__).resolve().parent


ASSETS_DIRECTORY_PATH = ROOT_DIRECTORY_PATH / 'assets'


ASSETS_OUTPUT_DIRECTORY_PATH = ASSETS_DIRECTORY_PATH / 'output'


ASSETS_OUTPUT_WWW_DIRECTORY_PATH = ASSETS_OUTPUT_DIRECTORY_PATH / 'www'


ASSETS_TEMPLATES_DIRECTORY_PATH = ASSETS_DIRECTORY_PATH / 'templates'


OUTPUT_DIRECTORY_PATH = ROOT_DIRECTORY_PATH.parent / 'output'


OUTPUT_WWW_DIRECTORY_PATH = OUTPUT_DIRECTORY_PATH / 'www'
